### ISSUE TITLE
Elements in a-tag

### ISSUE THREAD

**Issue by Martinaut** [onokumus/metismenujs#2]
**Describe the bug**
If there are other elements within the `a`-tag (e.g. `<a href="#">Text <i class="fa fa-archive"></i></a>`, the submenu will not show/hide if the users clicks on the element within the `a`-tag.

**To Reproduce**
Create a menu structure like this, where the `a`-tag contains another element:

```
<ul class="metismenu" id="menu">
    <li>
        <a href="#" class="has-arrow" aria-expanded="false">
            <i class="fa fa-archive"></i>
            Text
        </a>
        <ul>
             <li><a href="#">Link</a>
        </ul>
    </li>
</ul>
```

and intialize the menu: `new MetisMenu('#menu');`

Now click on the icon (`i`-tag) and the active-class won't be added to the `li`-tag.

**Expected behavior**
The expected behaviour is that the submenu shows or hides depending on the state.

**Desktop (please complete the following information):**
 - OS: Windows 10 1803
 - Browser Chrome
 - Version 68

**Additional context**
Stacktrace
```
Uncaught TypeError: Cannot read property 'parentNode' of null
    at e.t.toggle (index.js:97)
    at e.t.clickEvent (index.js:93)
```

Code available here: https://jsfiddle.net/aq9Laaew/125078/

**Comment by onokumus** [comment]
@Martinaut 
Thanks for bug report. I think I fixed it.

See https://jsfiddle.net/z6dqtfe3/
