### ISSUE TITLE
A CSS triangle for horizontal submenus pointing to the parent link like github menus

### ISSUE THREAD

**Issue by gurumark** [onokumus/metismenujs#4]
**Is your feature request related to a problem? Please describe.**
It is easier for users to see how the submenu is connected its parent link.

**Describe the solution you'd like**
A CSS triangle like in the github menus makes it visually easy to point to a submenu's parent link
**Describe alternatives you've considered**
There are no alternatives
**Additional context**
![screenshot from 2018-10-09 09-33-23](https://user-images.githubusercontent.com/1859151/46673023-d8f8e500-cba6-11e8-99f1-7437f7b77dec.png)

**Comment by onokumus** [comment]
https://onokumus.com/metismenujs/mm-github.html

**Comment by gurumark** [comment]
Cok iyi olmus, Osman. Bravo sana!!

**Comment by onokumus** [comment]
Thanks, especially for your Turkish message.

Please close the issue.
